---
name: Code Quality

on:
    - pull_request
    - push

jobs:
    lint:
        name: Lint
        runs-on: ubuntu-latest
        steps:
            - uses: actions/setup-node@v1
              with:
                  node-version: 12.x
            - uses: actions/checkout@v2
            - run: npm ci
            - run: npm run lint

# vim: set ft=yaml ts=4 sw=4 sts=4:
